// apps/ljh-design/app/not-found.tsx
'use client';
import { Button } from '@/app/_components/ui/button';
import { useRouter } from 'next/navigation';

export default function NotFound() {
  const router = useRouter();

  return (
    <div className="h-[100dvh] w-full flex items-center justify-center bg-background">
      <div className="text-center space-y-4">
        <h1 className="text-6xl font-bold text-primary">404</h1>
        <h2 className="text-2xl font-medium text-muted-foreground">页面未找到</h2>
        <p className="text-muted-foreground">抱歉，您访问的页面不存在</p>
        <Button onClick={() => router.push('/')} variant="default" className="mt-4">
          返回首页
        </Button>
      </div>
    </div>
  );
}

// apps/form/src/views/not-found.vue
<script setup lang="ts">
import { useRouter } from 'vue-router';

const router = useRouter();

const goBack = () => {
  router.back();
};

const goHome = () => {
  router.push('/');
};
</script>

<template>
    <div class="h-[100dvh] w-full flex flex-col items-center justify-center">
        <div class="text-9xl font-bold text-gray-200">404</div>
        <h1 class="mt-4 text-3xl font-bold tracking-tight text-gray-900">页面未找到</h1>
        <p class="mt-4 text-base text-gray-500">抱歉,我们找不到您要访问的页面。</p>
        <div class="mt-10 flex items-center justify-center gap-x-6">
            <button @click="goHome"
                class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
                返回首页
            </button>
            <button @click="goBack" class="text-sm font-semibold text-gray-900 hover:text-gray-500">
                返回上一页
            </button>
        </div>
    </div>
</template>
