// apps/ljh-design/app/_components/Comand/UserButton.tsx
'use client';
import { Avatar, AvatarFallback, AvatarImage } from '@/app/_components/ui/Avatar';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/app/_components/ui/dropdown-menu';
import { logout } from '@/app/_database/user';
import useUsers from '@/app/_hook/useUser';
import { User } from 'lucide-react';
import { redirect, useRouter } from 'next/navigation';
import toast from 'react-hot-toast';
import { LuLogOut } from 'react-icons/lu';
import { Skeleton } from '../ui/skeleton';

const UserButton = () => {
  const { user, loading } = useUsers({ redirects: false });
  const router = useRouter();

  return (
    <>
      {loading ? (
        <Skeleton className="size-10 rounded-full" />
      ) : (
        <DropdownMenu modal={false}>
          <DropdownMenuTrigger>
            <Avatar className="size-10 hover:opacity-80 transition-all duration-300 ">
              <AvatarImage alt="用户头像" src={user?.user.user_metadata.image} />
              <AvatarFallback>{user?.user.user_metadata.name}</AvatarFallback>
            </Avatar>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end" className="w-60">
            <DropdownMenuItem
              className="h-10 cursor-pointer"
              onClick={() => {
                router.push('/board/user');
              }}
            >
              <User className="size-4 mr-2 " />
              个人中心
            </DropdownMenuItem>
            <DropdownMenuItem
              className="h-10 cursor-pointer"
              onClick={async () => {
                await logout();
                toast.success('登出成功');
                redirect('/sign-in');
              }}
            >
              <LuLogOut className="size-4 mr-2 " />
              登出
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      )}
    </>
  );
};

export default UserButton;

// apps/form/src/components/common/UserButton.vue
<script setup lang="ts">
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Skeleton } from '@/components/ui/skeleton';
import { logout } from '@/database/supabase/user';
import { DEFAULT_AVATAR } from '@/lib';
import useUser from '@/stores/user';
import type { PropType } from 'vue';
import { useRouter } from 'vue-router';
const userData = useUser().userData;
type Side = 'end' | 'start' | 'center';
const router = useRouter();
const props = defineProps({
  side: {
    type: String as PropType<Side>,
    default: 'end',
  },
});
const logoutClick = async () => {
  await logout();
  router.push('/auth');
};
</script>
<template>
  <DropdownMenu>
    <DropdownMenuTrigger as-child>
      <Button variant="secondary" size="icon" class="rounded-full">
        <Avatar>
          <AvatarImage :src="userData!.session.user.user_metadata?.image || DEFAULT_AVATAR" alt="用户头像" />
          <AvatarFallback>
            <Skeleton class="h-full w-full" />
          </AvatarFallback>
        </Avatar>
        <span class="sr-only">切换用户菜单</span>
      </Button>
    </DropdownMenuTrigger>
    <DropdownMenuContent :align="props.side">
      <DropdownMenuLabel>我的账户</DropdownMenuLabel>
      <DropdownMenuSeparator />
      <DropdownMenuItem>设置</DropdownMenuItem>
      <DropdownMenuSeparator />
      <DropdownMenuItem class="cursor-pointer" @click="logoutClick">登出</DropdownMenuItem>
    </DropdownMenuContent>
  </DropdownMenu>
</template>

<style scoped></style>
