// apps/form/src/views/error.vue
<template>
    <div>
        <h1>错误</h1>
        <div class="h-[100dvh] w-full flex flex-col items-center justify-center">
            <div class="text-9xl font-bold text-gray-200">Error</div>
            <h1 class="mt-4 text-3xl font-bold tracking-tight text-gray-900">系统错误</h1>
            <p class="mt-4 text-base text-gray-500">抱歉,系统发生了一些错误。</p>
            <div class="mt-10">
                <button @click="goBack"
                    class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
                    返回上一页
                </button>
            </div>
        </div>

    </div>
</template>

<script lang="ts" setup>
import { useRouter } from 'vue-router';

const router = useRouter();

const goBack = () => {
  router.back();
};
</script>

// apps/jebet/src/page/error/Index.tsx
import { Button } from '@/components/ui/button';
import { useNavigate } from 'react-router-dom';

const Index = () => {
  const navigate = useNavigate();

  return (
    <div className='min-h-screen flex items-center justify-center bg-gray-100'>
      <div className='text-center p-8 bg-white rounded-lg shadow-lg'>
        <h1 className='text-6xl font-bold text-red-500 mb-4'>404</h1>
        <h2 className='text-2xl font-semibold text-gray-800 mb-4'>
          页面未找到
        </h2>
        <p className='text-gray-600 mb-8'>
          抱歉，您访问的页面不存在或已被移除。
        </p>
        <Button
          onClick={() => navigate('/')}
          className='px-6 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 transition-colors'
        >
          返回首页
        </Button>
      </div>
    </div>
  );
};

export default Index;
