// apps/ljh-design/components/Comand/UserButton.tsx
'use client';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/Avatar';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { logout } from '@/server/user';
import { User } from 'lucide-react';
import { redirect } from 'next/navigation';
import toast from 'react-hot-toast';
import { LuLogOut } from 'react-icons/lu';
import { Skeleton } from '../ui/skeleton';
import useUsers from '@/hook/useUser';

const UserButton = () => {
  const { user, loading } = useUsers({ redirects: false });

  return (
    <>
      {loading ? (
        <Skeleton className='size-10 rounded-full'></Skeleton>
      ) : (
        <DropdownMenu modal={false}>
          <DropdownMenuTrigger>
            <Avatar className='size-10 hover:opacity-80 transition-all duration-300 '>
              <AvatarImage
                alt='用户头像'
                src={user?.user.user_metadata.image}
              />
              <AvatarFallback>{user?.user.user_metadata.name}</AvatarFallback>
            </Avatar>
          </DropdownMenuTrigger>
          <DropdownMenuContent align='end' className='w-60'>
            <DropdownMenuItem
              className='h-10 cursor-pointer'
              onClick={() => {}}
            >
              <User className='size-4 mr-2 ' />
              个人中心
            </DropdownMenuItem>
            <DropdownMenuItem
              className='h-10 cursor-pointer'
              onClick={async () => {
                await logout();
                toast.success('登出成功');
                redirect('/sign-in');
              }}
            >
              <LuLogOut className='size-4 mr-2 ' />
              登出
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      )}
    </>
  );
};

export default UserButton;

// apps/note/src/components/common/UserButton.vue
<script setup lang="ts">
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { User } from "@supabase/supabase-js";
import {
  DropdownMenu,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
import DropdownMenuContent from "../ui/dropdown-menu/DropdownMenuContent.vue";
import { Skeleton } from "../ui/skeleton";
import { useRouter } from "vue-router";
import { logout } from "@/server/supabase/user";
const router = useRouter();
const props = defineProps<{
  user: User | undefined;
  isLoading: boolean;
}>();
const handleLogout = () => {
  logout();
  router.push("/login");
};
</script>
<template>
  <div v-if="!props.isLoading">
    <div v-if="props.user">
      <DropdownMenu>
        <DropdownMenuTrigger>
          <Avatar>
            <AvatarImage
              :src="props.user?.user_metadata.image"
              alt="@radix-vue"
            />
            <AvatarFallback>{{
              props.user?.user_metadata.name
            }}</AvatarFallback>
          </Avatar>
        </DropdownMenuTrigger>
        <DropdownMenuContent>
          <DropdownMenuItem as-child>
            <Button
              class="w-full cursor-pointer hover:bg-[#fff] dark:hover:bg-[#272727]"
              variant="ghost"
              @click="handleLogout"
            >
              退出
            </Button>
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
    <div class="h-10 w-10" v-else>
      <Button class="w-full h-full rounded-sm" variant="outline">登录</Button>
    </div>
  </div>
  <div v-else>
    <div class="h-10 w-10">
      <Skeleton class="h-full w-full rounded-full" />
    </div>
  </div>
</template>

<style lang="scss" scoped></style>
